# This is a basic workflow to help you get started with Actions
name: Build & Vet

# This workflow runs on each push
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Compiles code into binary
      - name: Build
        run: go build ./...
      # Checkes for subtle bugs that compile
      - name: Static Analysis
        run: go vet ./...
